@istest
private class testcalculator1{
public static testmethod void calculator1(){
    calculator1 varcal = new calculator1();
    varcal.num1 = 10;
    varcal.num2 = 11;
    varcal.add();
    varcal.sub();
    varcal.mul();
    varcal.div();
    calculator1 varcal1 = new calculator1();
    varcal1.num1 = 10;
    varcal1.num2 = 0;
    varcal1.add();
    varcal1.sub();
    varcal1.mul();
    varcal1.div();

    }
    }